### ISSUE TITLE
ip envs not added as DNS Entries

### ISSUE THREAD

**Issue by jasperf** [hiddeco/laravel-transip#13]
We use
```
......
use TransIP\Model\DnsEntry;
........
public static function registerDomain(DomainOrder $order, TransIPManager $transIPManager)
    {
        try {
            // Only purchase if production
            if (config('app.env') == 'production') {
                // Register via transip
                $transIpDomain = new \TransIP\Model\Domain($order->domain_name);
                $transIPManager->domain()->register($transIpDomain);
                // Add ANAME records to nameserver
            }

            $dnsEntryIP4 = new DnsEntry('@', 3600, 'A', config('server.ip4'));
            $dnsEntryIP6 = new DnsEntry('@', 3600, 'AAAA', config('server.ip6'));
            $transIPManager->domain()->setDnsEntries($order->domain_name, [$dnsEntryIP4, $dnsEntryIP6]);
        } catch (\Exception $exception) {
            \Bugsnag::notifyException($exception);
        }
```
To add custom domains with DNS entries. Somehow the TransIP standard DNS entries prevail and so each new domain is not added with the ip addresses added to our .env file, but the standard DNS ipv4 and ipv6 added in TransIP under `transip.nl/cp/domein-hosting/standaard-domeininstellingen/dns-instellingen/` . Any ideas why that is the case?

**P.S.** Using latest Laravel 5.6 and         `"hiddeco/laravel-transip": "^5.6",`

**Comment by petericebear** [comment]
You can’t change that functionality unfortunatly. Same kind of thing happens when you order a server. You Get An ok status back but nothing more. Sometimes minutes later you can get al the servers and check of the description is empty.

You have to get the domain a fee seconde later and edit the DNS entries you want to change.

**Comment by jasperf** [comment]
Thanks @petericebear . I was afraid of that. Will see if we can do the domain booking , wait a few seconds, do  api ips update and then again a bit later the LE SSL part . Will post back when I have more news .

**Comment by petericebear** [comment]
If it is a new domain, you can add a sleeptimer for 10 seconds then you are save. Already been there ;)

**Comment by petericebear** [comment]
Can we close this issue?

**Comment by jasperf** [comment]
Yes. Thanks for all the feedback!
