### ISSUE TITLE
Laravel 6.x support

### ISSUE THREAD

**Issue by jasperf** [hiddeco/laravel-transip#15]
Upgrading to Laravel 6.x here and going through all my packages. Laravel TransIp could use a version bump as well. Looking into it as for other packages, but thought it good to start the issue here.

**Comment by petericebear** [comment]
Hi Jasper,
Would be great if you can send in a PR for it.

**Comment by jasperf** [comment]
Working on a branch at https://github.com/jasperf/laravel-transip . Changed travis.cli and composer so far. Did Illuminate package Laravel 6.0 addition and PHP upgrade based on https://laravel.com/docs/6.0/upgrade mainly. Laravel needs 7.2 up. Never made nor updated Laravel Packages. Recommendations for testing are welcome @petericebear .

**Comment by petericebear** [comment]
A new version based on a Pull Request has been merged and released. Thanks for the effort!
