### ISSUE TITLE
Laravel 5.2 version

### ISSUE THREAD

**Issue by bobbybouwmann** [hiddeco/laravel-transip#3]
Hi,

I'm working with the newest Laravel (5.2) and I want to use your package. However I can't install it with composer since the release (0.1) only contains the support for Laravel 5.0 and 5.1. This means that I need to work with the dev-master support. I rather wouldn't do that!

Is it possible to create a new release for Laravel 5.2 so the package can be required with composer?

Thanks in advantage!

**Comment by hiddeco** [comment]
Hi @bobbybouwmann!

I would recommend to use the `dev-master` version of the package as this one supports Laravel 5.2 :smile: 

I will push out a new tagged release as soon as I find some time to update the TransIP API package to TransIPs new 5.2 API (probably this weekend).

**Comment by bobbybouwmann** [comment]
Great!
